# Generated by Django 4.2.16 on 2024-11-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукции')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='main/images', verbose_name='Изображение продукции')),
                ('type_object', models.CharField(max_length=100, verbose_name='Тип продукции')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукции',
                'abstract': False,
            },
        ),
    ]
