# Generated by Django 4.2.16 on 2024-11-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название работы')),
                ('description', models.CharField(max_length=255, verbose_name='Описание работы')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='img/', verbose_name='Изображение работы')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='production',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='img/', verbose_name='Изображение продукции'),
        ),
    ]
