# Generated by Django 4.2.16 on 2024-11-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ourworks_alter_production_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourworks',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media/', verbose_name='Изображение работы'),
        ),
        migrations.AlterField(
            model_name='production',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='media/', verbose_name='Изображение продукции'),
        ),
    ]
