# Generated by Django 4.2.16 on 2024-11-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_ourworks_image_alter_production_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Услуга')),
                ('description', models.CharField(max_length=255, verbose_name='Описание услуги')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='media/', verbose_name='Изображение услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='production',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Изображение продукции'),
        ),
    ]
