# Generated by Django 4.2.16 on 2024-11-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_services_alter_production_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(max_length=1055, verbose_name='Описание услуги'),
        ),
    ]
